#!/bin/bash

# Look for new ROMs since the last run.

##### Config #####
# Don't edit the configuration in this file as it would be overwritten on updates.
# Create the file .config/onionscraper.conf or .onionscraper.conf and override the variables.

module=screenscraper
gamelist="true"
exclude=(PORTS PICO)

# Skyscraper config file (no quotes)
skyscraperini=~/.skyscraper/config.ini

##################
if [[ -f ~/.config/onionscraper.conf ]]; then
    source ~/.config/onionscraper.conf
elif [[ -f ~/.onionscraper.conf ]]; then
    source ~/.onionscraper.conf
fi

#---------------

function usage() {
    echo "Usage: $(basename $0) [OPTIONS] [SYSTEMS]"
    echo "Scrape artwork for new ROMs or for given systems. Helps mananaging artwork."
    echo "options:"
    echo "  -a --all:    check all platforms instead of just the ones with new ROMs."
    echo "  -c --clean:  remove images for deleted games."
    echo "  -p --pretend with clean, find but don't delete images."
    echo "  -v --vacuum  vacuum the Skyscraper cache (danger?)."
    echo "  -i --import: import manually added assets."
    echo "  -s --skip:   skip existing output files."
    echo "  -d --device  use the Skyscraper config for the given device."
    echo "  -h --help:   this help."
    echo "systems:"
    echo "  All parameters after the last option are treated as a list of systems"
    echo "  to process. Ignored if the 'all' option is used."
    exit 0
}

# convert the Miyoo systems into Skyscraper platforms
# One system can combine multiple platforms, in which case define them
# as a space-separated double-quoted string, for example "ngp ngpc".
declare -A systemlist
systemlist[AMIGA]=amiga
systemlist[CPC]=amstradcpc
systemlist[ARCADE]=mame-libretro
systemlist[ATARI]=atari2600
systemlist[FIFTYTWOHUNDRED]=atari5200
systemlist[SEVENTYEIGHTHUNDRED]=atari7800
systemlist[LYNX]=atarilynx
systemlist[WS]="wonderswan wonderswancolor"
systemlist[COLECO]=coleco
systemlist[VECTREX]=vextrex
systemlist[INTELLIVISION]=intellivision
systemlist[MSX]=msx
systemlist[PCECD]=pcenginecd
systemlist[PCE]=pcengine
systemlist[FC]=nes
systemlist[GB]="gb gbc"
systemlist[GBC]=gbc
systemlist[GBA]=gba
systemlist[POKE]=pokemini
systemlist[SFC]=snes
systemlist[VB]=virtualboy
systemlist[PICO]=pico8
systemlist[PORTS]=ports
systemlist[SCUMMVM]=scummvm
systemlist[THIRTYTWOX]=sega32x
systemlist[SEGACD]=segacd
systemlist[GG]=gamegear
systemlist[MD]=megadrive
systemlist[MS]=mastersystem
systemlist[SEGASGONE]=sg-1000
systemlist[ZXS]=zxspectrum
systemlist[NEOGEO]=neogeo
systemlist[NEOCD]=neogeocd
systemlist[NGP]="ngp ngpc"
systemlist[PS]=psx
systemlist[VIDEOPAC]=videopac

function check_rompath() {
    if [[ -d "$rompath" ]]; then
	    if [[ ! "$(ls -A $rompath)" ]]; then
            echo "The path to the ROMs is empty. Check your configuration."
            exit 1
	    fi
    else
	    echo "The path to the ROMs does not exist. Check your configuration."
        echo "Not found: $rompath"
        exit 1
    fi
}

function scrape_platform() {
    echo "(Skyscraper platform: $platform)"
    if [[ ! -d "$rompath/$system" ]]; then
        echo "Folder for system $system doesn't exist."
        echo "Check your configuration, ROM paths and mount points."
        return
    fi
	if [[ ! "$(ls -A $rompath/$system)" ]]; then
        echo "No game in $system."
        return
    fi

    Skyscraper ${inifile} -p ${platform} -s ${module} \
        -i $rompath/$system \
        --flags $skip_in
    Skyscraper ${inifile} -p ${platform} \
        -i $rompath/$system -o $rompath/$system/Imgs \
        --flags $skip_out
    mv $rompath/$system/Imgs/screenshots/* $rompath/$system/Imgs/
    rmdir $rompath/$system/Imgs/covers \
          $rompath/$system/Imgs/marquees \
          $rompath/$system/Imgs/screenshots \
          $rompath/$system/Imgs/textures \
          $rompath/$system/Imgs/wheels

    if [[ "$gamelist" == "true" && -f $rompath/$system/gamelist.xml ]]; then
        # if using a gamelist, clean it up and rename it
        sed -i 's/Imgs\/screenshots/Imgs/g' $rompath/$system/gamelist.xml
        if [[ ! "$hasxmlstarlet" == "true" ]]; then
            mv $rompath/$system/gamelist.xml $rompath/$system/miyoogamelist.$platform.xml
        else
            xmlstarlet  edit -d "//desc" -d "//rating" -d "//genre" -d "//players" -d "//releasedate" -d "//developer" -d "//publisher" -d "//hash" -d "//thumbnail" -d "//genreid" -d "//marquee" -d "//texture" -d "//video" --subnode "gameList/game[not(image)]" -t elem -n image -v "no-img.png" $rompath/$system/gamelist.xml > $rompath/$system/miyoogamelist.$platform.xml
            rm $rompath/$system/gamelist.xml
        fi
    else
        # if not using a gamelist, just delete it
        rm $rompath/$system/gamelist.xml
    fi
}

function find_match {
    platform=$1
    asset=$2
    game=${asset#$pdir$adir/}
    game=${game%.*}
    game="$(printf '%q' "${game}")" # escapes special characters
    res=$(find "$rompath/$platform" -name "${game}.*" |wc -l)
    if [[ "$res" == "0" ]]; then
        echo "rm \"$asset\"" >> $orphansfile
    fi
}

function clean_assets() {

    for pdir in $rompath/*/
    do

        system=$(basename $pdir)
        if [[ "$systems" != "" ]]; then
            # a list of systems was provided, skip all that are not in the list
            if [[ ! " $systems " =~ " $system " ]]; then       
                continue
            fi
        fi

        # check the exclude list
        skip="false"
        for i in "${exclude[@]}"
        do
            if [ "$i" == "$system" ] ; then
                echo "Skipping $system"
                skip="true"
                continue
            fi
        done
        if $skip ; then
            continue
        fi

        echo Cleaning $system
        for asset in ${pdir}Imgs/*
        do
            # Special case: directory is empty
            if [[ "$asset" != "${pdir}Imgs/*" ]]; then
                game=${asset#${pdir}Imgs/}
                game=${game%.*}
                game="$(printf '%q' "${game}")" # escapes special characters
                #res=$(find "$rompath/$system" -name "${game}.*" |wc -l)
                res=$(find "$rompath/$system" -maxdepth 1 -name "${game}.*" |wc -l)
                if [[ "$res" == "0" ]]; then
                    if [[ "$dryrun" == "true" ]]; then
                        echo "ORPHANED ARTWORK: $asset"
                    else
                        echo "DELETING $asset"
                        rm "$asset"
                    fi
                fi

            fi

        done
    done
    exit 0
}

function vacuum_skyscraper_cache() {
    echo "Skyscraper cache vacuum"
    for pdir in $rompath/*/
    do
        system=$(basename "$pdir")
        platforms=${systemlist[$system]}
        if [[ "$platforms" == "" ]]; then
            echo "Unsupported system"
        else
            for platform in $platforms
            do
                echo vacuum $platform
                Skyscraper ${inifile} -p $platform -i $rompath/$system --cache vacuum --flags unattendskip
            done
        fi

    done
    exit 0
}

# ---------------------------------------------------------

allplatforms="false"
skip_in="unattendskip"
skip_out="unattend"
import="false"
clean="false"
dryrun="false"
vacuum="false"
uselastrun="true"
hasxmlstarlet="false"
system=""


while [[ "$1" = "-"* ]]; do
    if [[ "$1" = "--help" || "$1" = "-h"  ]]; then
        usage
    elif [[ "$1" == "--all" || "$1" == "-a" ]]; then
        echo "Scanning all platforms."
        allplatforms="true"
        shift
    elif [[ "$1" == "-s" || "$1" == "--skip" ]]; then
        skip_out="unattendskip"
        shift
    elif [[ "$1" == "-i" || "$1" == "--import" ]]; then
        import="true"
        module="import"
        skip_in="unattend"
        shift
    elif [[ "$1" == "-c" || "$1" == "--clean" ]]; then
        clean="true"
        shift
    elif [[ "$1" == "-p" || "$1" == "--pretend" ]]; then
        dryrun="true"
        shift
    elif [[ "$1" == "-d" || "$1" == "--device" ]]; then
        skyscraperini=${skyscraperini%.ini}.$2.ini
        shift 2
    elif [[ "$1" == "-v" || "$1" == "--vacuum" ]]; then
        vacuum="true"
        shift
    else
        echo "Unsupported option $1."
        shift
    fi
done

# remaining parameters are systems to scrape
if [[ "$allplatforms" != "true" ]]; then
    systems="$@"
    if [[ "$systems" != "" ]]; then
        uselastrun="false"
    fi
fi

#---------------

if [[ ! -f $skyscraperini ]]; then
    echo "Could not find Skyscraper config file: $skyscraperini"
    echo "Aborting."
    exit 1
fi

inifile="-c $skyscraperini"

inputline=$(grep -m 1 ^inputFolder "$skyscraperini")
rompath=${inputline##*=}
rompath="${rompath%\"}"
rompath="${rompath#\"}"
check_rompath

lastrun=$rompath/.onionscraper.lastrun 

if [[ "$allplatforms" == "true" ]]; then
    rm -f $lastrun
fi

if [[ "$clean" == "true" ]]; then
    clean_assets
elif [[ "$vacuum" == "true" ]]; then
    vacuum_skyscraper_cache
fi

if xmlstarlet_loc="$(type -p "xmlstarlet")" || [[ -n $xmlstarlet_loc ]]; then
    hasxmlstarlet="true"
fi

if [[ ! -f ${lastrun} && "$systems" == "" ]] || [[ "$allplatforms" == "true" ]]; then
    echo "Checking all systems: this could take a long time..."
    cd ${rompath}
    systems=$(find -mindepth 1 -maxdepth 1 -type d -printf "%P ")
    cd -
fi

if [[ "$systems" == "" ]]; then
    echo Looking for new ROMs in $rompath

    systems=$(find ${rompath} -mindepth 2 -maxdepth 2 -type f -cnewer ${lastrun} -exec sh -c 'basename $(dirname "$0")' {} \; | sort | uniq)

    if [[ "$systems" == "" ]];then
        echo "No new game found."
        touch ${lastrun}
        exit 0
    fi
fi

skip=false
for system in $systems
do
    for i in "${exclude[@]}"
    do
        if [ "$i" == "$system" ] ; then
            echo "Skipping $system"
            skip=true
        fi
    done
    if ! $skip ; then
        echo -n "Processing $system ... "

        platforms=${systemlist[$system]}
        if [[ "$platforms" == "" ]]; then
            echo "Unsupported system"
        else
            # Miyoo systems can be formed of more than one Skyscraper platform
            for platform in $platforms
            do
                scrape_platform
            done
            if [[ "$gamelist" == "true" ]]; then
                if ! ls $rompath/$system/miyoogamelist.*.xml >/dev/null 2>&1; then
                    # No gamelist available, maybe there were no games in the directory
                    continue
                fi
                echo "<?xml version=\"1.0\"?>" >$rompath/$system/miyoogamelist.xml
                echo "<gameList>" >>$rompath/$system/miyoogamelist.xml
                for gamelist in $rompath/$system/miyoogamelist.*.xml
                do
                    if [[ "$hasxmlstarlet" != "true" ]]; then
                        # No xmlstarlet, print the entire xml file minus the first 2 and last lines.
                        # Does this work on Mac OS?
                        tail -n +3 $gamelist | head -n -1 >>$rompath/$system/miyoogamelist.xml
                    else
                        xmlstarlet select -t --copy-of '//gameList/game' $gamelist >>$rompath/$system/miyoogamelist.xml
                    fi
                done
                echo "</gameList>" >>$rompath/$system/miyoogamelist.xml
                rm $rompath/$system/miyoogamelist.*.xml
            fi
        fi
    fi
    skip=false
done

# Update lastrun
if [[ "$uselastrun" == "true" ]]; then
    echo "Updating last run time."
    touch ${lastrun}
fi

